# Variables
@baseUrl = http://localhost:3333
@origin = http://localhost:5173
@token = {{auth.response.body.$.token}}
@projectId = {{createProject.response.body.$.projectId}}

###

# @name auth
POST {{baseUrl}}/sessions/github
Content-Type: application/json
Origin: {{origin}}

{
  "code": "e4ed5d62a0b8fd3ec70b"
}

###

# @name getProfile
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}
Origin: {{origin}}

{
  "name": "Project API",
  "description": "project description",
  "type": "backend",
  "techsIds": [
    "csaqplggm5cnk5gvk1mee53l",
    "dg0mtkuujsnnsmiyrj31e4gn",
    "y7h76rpe9bpu0nyoge75r8uo",
    "r4dril0oqwn98r4d8nz8d0wn"
  ],
  "githubUrl": "https://github.com/sercomp"
}

###

# @name findProjectsByUserId
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name findProjectById
GET {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name updateProject
PUT {{baseUrl}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}
Origin: {{origin}}

{
  "name": "Project API Updated",
  "description": "Project description updated",
  "type": "backend",
   "techsIds": [
    "csaqplggm5cnk5gvk1mee53l",
    "dg0mtkuujsnnsmiyrj31e4gn",
    "y7h76rpe9bpu0nyoge75r8uo"
  ],
  "githubUrl": "https://github.com/project-updated"
}

###

# @name deleteProject
DELETE {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name findAllTechs
GET {{baseUrl}}/techs
Origin: {{origin}}

###

# @name getUserRepositories
GET {{baseUrl}}/repos
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name getRepositoryData
GET {{baseUrl}}/repos/portfolio
Authorization: Bearer {{token}}
Origin: {{origin}}
