# Variables
@baseUrl = http://localhost:3333
@origin = http://localhost:5173
@token = {{auth.response.body.$.token}}
@projectId = {{createProject.response.body.$.projectId}}

###

# @name auth
POST {{baseUrl}}/sessions/github
Content-Type: application/json
Origin: {{origin}}

{
  "code": "fd126218c6cd5c57aead"
}

###

# @name getProfile
GET {{baseUrl}}/profile
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}
Origin: {{origin}}

{
  "name": "Project 1",
  "description": "project description",
  "type": "fullstack",
  "githubUrl": "https://github.com/sercomp"
}

###

# @name findProjectsByUserId
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name findProjectById
GET {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}
Origin: {{origin}}

###

# @name updateProject
PUT {{baseUrl}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}
Origin: {{origin}}

{
  "name": "Project updated",
  "description": "project description updated",
  "type": "backend",
  "githubUrl": "https://github.com/project-updated"
}

###

# @name deleteProject
DELETE {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}
Origin: {{origin}}